package business;

import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.parser.PdfTextExtractor;
import java.io.ByteArrayOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import model.ActivityLog;
import model.User;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Unit tests for PdfReportBuilder — no database required.
 *
 * Covers SRS test cases:
 *   TC-REP-001  PDF is generated and downloaded (non-empty, valid PDF bytes)
 *   TC-REP-002  Password is not printed in any report
 *   TC-REP-003  Only username and role appear in user list
 *   TC-REP-004  Asterisk (*) beside the currently logged-in admin
 *   TC-REP-007  PDF uses landscape orientation
 *   TC-REP-008  Header and footer from web.xml appear in the PDF
 *   TC-REP-010  PDF is not permanently saved (stream-only, no file on disk)
 *   TC-TIME-002 Empty result handled gracefully (no crash, valid PDF produced)
 *   NFR-ERR-004 Empty row message shown when dataset is empty
 */
public class PdfReportBuilderTest {

    private static final String HEADER      = "Active Learning, Inc. — Course Management System";
    private static final String FOOTER      = "Generated by Active Learning, Inc. System | ICS2609 Final Project";
    private static final String LOGGED_IN   = "sys.admin1@school.edu";
    private static final String KNOWN_HASH  = "ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f";

    private static PdfReportBuilder builder;

    @BeforeClass
    public static void setUp() {
        builder = new PdfReportBuilder();
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private User makeUser(String email, String role) {
        User u = new User();
        u.setEmail(email);
        u.setAppRole(role);
        return u;
    }

    private byte[] buildUserReport(List<User> users) throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateUserReport(out, users, LOGGED_IN, HEADER, FOOTER,
                "All Records Test");
        return out.toByteArray();
    }

    private String extractAllText(byte[] pdfBytes) throws Exception {
        PdfReader reader = new PdfReader(pdfBytes);
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i <= reader.getNumberOfPages(); i++) {
            sb.append(PdfTextExtractor.getTextFromPage(reader, i));
        }
        reader.close();
        return sb.toString();
    }

    // ── TC-REP-001: valid PDF is produced ────────────────────────────────

    @Test
    public void generateUserReport_producesNonEmptyBytes() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(makeUser("a@b.com", "Admin")));
        assertTrue("PDF output must not be empty", bytes.length > 0);
    }

    @Test
    public void generateUserReport_startsWithPdfMagicBytes() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(makeUser("a@b.com", "Admin")));
        String header4 = new String(bytes, 0, Math.min(4, bytes.length));
        assertEquals("Output must start with PDF magic bytes %PDF", "%PDF", header4);
    }

    @Test
    public void generateGradeReport_producesValidPdf() throws Exception {
        List<String[]> rows = new ArrayList<String[]>();
        rows.add(new String[]{"Intro to Java", "Hello World", "100", "Graded", "95", "Good work"});
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateGradeReport(out, rows, "student01@mail.com", HEADER, FOOTER,
                "Grade Report Test");
        byte[] bytes = out.toByteArray();
        assertTrue("Grade report must produce bytes", bytes.length > 0);
        assertEquals("%PDF", new String(bytes, 0, 4));
    }

    @Test
    public void generateLogReport_producesValidPdf() throws Exception {
        List<ActivityLog> logs = new ArrayList<ActivityLog>();
        ActivityLog log = new ActivityLog();
        log.setUsername("sys.admin1@school.edu");
        log.setActivity("LOGIN_SUCCESS");
        log.setIpAddress("127.0.0.1");
        log.setUserRole("Admin");
        log.setModule("LoginServlet");
        log.setActivityTime(new java.sql.Timestamp(System.currentTimeMillis()));
        logs.add(log);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateLogReport(out, logs, LOGGED_IN, HEADER, FOOTER, "Log Report Test");
        byte[] bytes = out.toByteArray();
        assertTrue("Log report must produce bytes", bytes.length > 0);
        assertEquals("%PDF", new String(bytes, 0, 4));
    }

    @Test
    public void generateClassListReport_producesValidPdf() throws Exception {
        List<String[]> rows = new ArrayList<String[]>();
        rows.add(new String[]{"Java 101", "student01@mail.com", "2026-01-10", "active"});
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateClassListReport(out, rows, LOGGED_IN, HEADER, FOOTER,
                "Class List Test");
        byte[] bytes = out.toByteArray();
        assertTrue("Class list report must produce bytes", bytes.length > 0);
        assertEquals("%PDF", new String(bytes, 0, 4));
    }

    // ── TC-REP-002: no password in report ────────────────────────────────

    @Test
    public void generateUserReport_doesNotContainKnownPasswordHash() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(
                makeUser("sys.admin1@school.edu", "Admin")));
        // iText encodes text in PDF streams; check raw bytes for the hash
        String raw = new String(bytes, "ISO-8859-1");
        assertFalse("PDF must not contain known password hash", raw.contains(KNOWN_HASH));
    }

    @Test
    public void generateUserReport_doesNotContainWordPassword() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(makeUser("a@b.com", "Admin")));
        String text = extractAllText(bytes);
        assertFalse("Extracted PDF text must not contain 'password'",
                text.toLowerCase().contains("password"));
    }

    // ── TC-REP-003: only username and role in user list ───────────────────

    @Test
    public void generateUserReport_columnsAreUsernameAndRole() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(
                makeUser("prof.turing@school.edu", "Admin")));
        String text = extractAllText(bytes);
        assertTrue("Column header 'Username / Email' must be present",
                text.contains("Username") || text.contains("Email"));
        assertTrue("Column header 'Application Role' must be present",
                text.contains("Role") || text.contains("Application"));
    }

    // ── TC-REP-004: asterisk beside logged-in admin ───────────────────────

    @Test
    public void generateUserReport_asteriskBesideLoggedInAdmin() throws Exception {
        List<User> users = new ArrayList<User>();
        users.add(makeUser(LOGGED_IN, "Admin"));
        users.add(makeUser("other.admin@school.edu", "Admin"));
        byte[] bytes = buildUserReport(users);
        String text = extractAllText(bytes);
        assertTrue("PDF must contain '*' marker for logged-in admin", text.contains("*"));
    }

    @Test
    public void generateUserReport_asteriskOnlyOnLoggedInAdmin() throws Exception {
        List<User> users = new ArrayList<User>();
        users.add(makeUser(LOGGED_IN, "Admin"));
        users.add(makeUser("other.admin@school.edu", "Admin"));
        byte[] bytes = buildUserReport(users);
        String text = extractAllText(bytes);
        // logged-in user appears with asterisk
        assertTrue("Logged-in admin must appear with asterisk",
                text.contains(LOGGED_IN + " *") || text.contains(LOGGED_IN + "*"));
        // other user must NOT have asterisk
        assertFalse("Other admin must not have asterisk",
                text.contains("other.admin@school.edu *") ||
                text.contains("other.admin@school.edu*"));
    }

    // ── TC-REP-007: landscape orientation ────────────────────────────────

    @Test
    public void generateUserReport_isLandscapeOrientation() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(makeUser("a@b.com", "Admin")));
        PdfReader reader = new PdfReader(bytes);
        com.itextpdf.text.Rectangle pageSize = reader.getPageSizeWithRotation(1);
        reader.close();
        assertTrue("PDF page width must be greater than height (landscape)",
                pageSize.getWidth() > pageSize.getHeight());
    }

    @Test
    public void generateGradeReport_isLandscapeOrientation() throws Exception {
        List<String[]> rows = new ArrayList<String[]>();
        rows.add(new String[]{"Course", "Assignment", "100", "Graded", "90", "Nice"});
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateGradeReport(out, rows, "student01@mail.com", HEADER, FOOTER, "Test");
        PdfReader reader = new PdfReader(out.toByteArray());
        com.itextpdf.text.Rectangle pageSize = reader.getPageSizeWithRotation(1);
        reader.close();
        assertTrue("Grade report must be landscape", pageSize.getWidth() > pageSize.getHeight());
    }

    // ── TC-REP-008: header and footer from web.xml ────────────────────────

    @Test
    public void generateUserReport_containsPdfHeader() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(makeUser("a@b.com", "Admin")));
        String text = extractAllText(bytes);
        assertTrue("PDF must contain the header string from web.xml",
                text.contains("Active Learning"));
    }

    @Test
    public void generateUserReport_containsPdfFooterAndGeneratedBy() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(makeUser("a@b.com", "Admin")));
        String text = extractAllText(bytes);
        assertTrue("PDF must contain 'Generated By:' with the logged-in username",
                text.contains("Generated By:") || text.contains(LOGGED_IN));
    }

    @Test
    public void generateUserReport_containsPageNumbering() throws Exception {
        byte[] bytes = buildUserReport(Arrays.asList(makeUser("a@b.com", "Admin")));
        String text = extractAllText(bytes);
        assertTrue("PDF must contain 'Page' numbering (Page x of y)",
                text.contains("Page") || text.contains("page"));
    }

    // ── TC-REP-010 / FR-REP-009: not saved on server (stream-only) ────────

    @Test
    public void generateUserReport_writesOnlyToProvidedStream() throws Exception {
        // The builder must write only to the provided OutputStream, not to any file.
        // We verify this by passing a ByteArrayOutputStream and ensuring the file
        // system has no side effect — implied by the architecture, but test confirms
        // the output stream contains a complete PDF.
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateUserReport(out, Arrays.asList(makeUser("a@b.com", "Admin")),
                LOGGED_IN, HEADER, FOOTER, "Server-Side Save Test");
        assertTrue("Stream must be populated (PDF delivered to stream only)",
                out.toByteArray().length > 100);
    }

    // ── TC-TIME-002 / NFR-ERR-004: empty data handled gracefully ─────────

    @Test
    public void generateUserReport_emptyList_producesValidPdf() throws Exception {
        byte[] bytes = buildUserReport(Collections.<User>emptyList());
        assertTrue("Empty user list must still produce a valid PDF", bytes.length > 0);
        assertEquals("Empty user report must start with %PDF",
                "%PDF", new String(bytes, 0, 4));
    }

    @Test
    public void generateGradeReport_emptyList_producesValidPdf() throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateGradeReport(out, Collections.<String[]>emptyList(),
                "student@mail.com", HEADER, FOOTER, "Empty Grade Report");
        byte[] bytes = out.toByteArray();
        assertTrue("Empty grade list must still produce a valid PDF", bytes.length > 0);
        assertEquals("%PDF", new String(bytes, 0, 4));
    }

    @Test
    public void generateLogReport_emptyList_producesValidPdf() throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateLogReport(out, Collections.<ActivityLog>emptyList(),
                LOGGED_IN, HEADER, FOOTER, "Empty Log Report");
        byte[] bytes = out.toByteArray();
        assertTrue("Empty log list must still produce a valid PDF", bytes.length > 0);
        assertEquals("%PDF", new String(bytes, 0, 4));
    }

    @Test
    public void generateClassListReport_emptyList_producesValidPdf() throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateClassListReport(out, Collections.<String[]>emptyList(),
                LOGGED_IN, HEADER, FOOTER, "Empty Class List");
        byte[] bytes = out.toByteArray();
        assertTrue("Empty class list must still produce a valid PDF", bytes.length > 0);
        assertEquals("%PDF", new String(bytes, 0, 4));
    }

    // ── TC-REP-009 / FR-PDF-007/008: filename format ─────────────────────

    @Test
    public void filenameTimestamp_followsYYYYMMDDHHMMSSFormat() {
        // Verify the timestamp format string matches the SRS requirement
        String ts = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
        assertTrue("Timestamp must be exactly 14 digits", ts.matches("\\d{14}"));
        assertTrue("Year must be 4 digits", ts.substring(0, 4).matches("\\d{4}"));
        assertTrue("Month must be 2 digits (01-12)", ts.substring(4, 6).matches("(0[1-9]|1[0-2])"));
        assertTrue("Day must be 2 digits (01-31)", ts.substring(6, 8).matches("(0[1-9]|[12]\\d|3[01])"));
    }

    @Test
    public void filenameFormat_allRecordsReport_matchesConvention() {
        String ts = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
        String filename = "ALL_RECORDS_" + ts + ".pdf";
        assertTrue("Filename must start with report name", filename.startsWith("ALL_RECORDS_"));
        assertTrue("Filename must end with .pdf", filename.endsWith(".pdf"));
        assertTrue("Filename must contain 14-digit timestamp",
                filename.matches(".*_\\d{14}\\.pdf"));
    }

    @Test
    public void filenameFormat_gradeReport_matchesConvention() {
        String ts = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
        String filename = "GRADE_REPORT_" + ts + ".pdf";
        assertTrue(filename.matches(".*_\\d{14}\\.pdf"));
    }

    // ── TC-REP-006 / generateOwnRecordReport ──────────────────────────────

    @Test
    public void generateOwnRecordReport_producesValidPdf() throws Exception {
        List<User> userList = new ArrayList<User>();
        userList.add(makeUser(LOGGED_IN, "Admin"));
        List<ActivityLog> logs = new ArrayList<ActivityLog>();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateOwnRecordReport(out, userList, logs, LOGGED_IN,
                HEADER, FOOTER, "Administrator Account Record");
        byte[] bytes = out.toByteArray();
        assertTrue("Own record report must produce bytes", bytes.length > 0);
        assertEquals("%PDF", new String(bytes, 0, 4));
    }

    @Test
    public void generateOwnRecordReport_containsLoggedInEmail() throws Exception {
        List<User> userList = new ArrayList<User>();
        userList.add(makeUser(LOGGED_IN, "Admin"));
        List<ActivityLog> logs = new ArrayList<ActivityLog>();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        builder.generateOwnRecordReport(out, userList, logs, LOGGED_IN,
                HEADER, FOOTER, "Administrator Account Record");
        String text = extractAllText(out.toByteArray());
        assertTrue("Own record report must contain the admin's email",
                text.contains("sys.admin1") || text.contains("school.edu"));
    }
}
