package business;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.LineSeparator;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import model.ActivityLog;
import model.User;

public class PdfReportBuilder {

    public PdfReportBuilder() {}



    private static class HeaderFooterPageEvent extends PdfPageEventHelper {
        private final String headerText;
        private final String footerText;
        private final String currentUser;
        private final String generatedDateStr;
        private PdfTemplate totalPagesPlaceholder;
        private BaseFont baseFont;

        HeaderFooterPageEvent(String headerText, String footerText,
                               String currentUser, String generatedDateStr) {
            this.headerText       = headerText;
            this.footerText       = footerText;
            this.currentUser      = currentUser;
            this.generatedDateStr = generatedDateStr;
            try {
                this.baseFont = BaseFont.createFont(
                        BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            totalPagesPlaceholder = writer.getDirectContent().createTemplate(30, 16);
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            float xHeader      = document.left();
            float yHeader      = document.top() + 15;
            float xFooterLeft  = document.left();
            float yFooter      = document.bottom() - 20;
            float xFooterRight = document.right() - 36;

            ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT,
                    new Phrase(headerText,
                            new Font(Font.FontFamily.HELVETICA, 9, Font.ITALIC, BaseColor.GRAY)),
                    xHeader, yHeader, 0);

            String metaFooter = footerText + " | Generated By: " + currentUser
                    + " on " + generatedDateStr;
            ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT,
                    new Phrase(metaFooter,
                            new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.DARK_GRAY)),
                    xFooterLeft, yFooter, 0);

            String pageStr = "Page " + writer.getPageNumber() + " of ";
            ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_RIGHT,
                    new Phrase(pageStr,
                            new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.DARK_GRAY)),
                    xFooterRight, yFooter, 0);

            writer.getDirectContent().addTemplate(totalPagesPlaceholder, xFooterRight + 6, yFooter);
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            totalPagesPlaceholder.beginText();
            totalPagesPlaceholder.setFontAndSize(baseFont, 8);
            totalPagesPlaceholder.setColorFill(BaseColor.DARK_GRAY);
            totalPagesPlaceholder.showText(String.valueOf(writer.getPageNumber()));
            totalPagesPlaceholder.endText();
        }
    }



    private Document openDocument() {
        return new Document(PageSize.A4.rotate(), 36, 36, 54, 36);
    }

    private void setupPageEvent(Document document, OutputStream os,
            String headerText, String footerText, String currentUser) throws Exception {
        PdfWriter writer = PdfWriter.getInstance(document, os);
        String dateStr = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        writer.setPageEvent(
                new HeaderFooterPageEvent(headerText, footerText, currentUser, dateStr));
    }

    private void addTitle(Document document, String titleText) throws DocumentException {
        Paragraph title = new Paragraph(titleText,
                new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, BaseColor.DARK_GRAY));
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(20);
        document.add(title);
    }

    private void addReportHeader(Document document, String orgLine, String reportName,
            String generatedBy, String reportType) throws DocumentException {
        Paragraph orgTitle = new Paragraph(orgLine,
                new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD, new BaseColor(44, 62, 80)));
        orgTitle.setAlignment(Element.ALIGN_CENTER);
        orgTitle.setSpacingAfter(4);
        document.add(orgTitle);

        Paragraph rName = new Paragraph(reportName,
                new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, new BaseColor(89, 107, 121)));
        rName.setAlignment(Element.ALIGN_CENTER);
        rName.setSpacingAfter(10);
        document.add(rName);

        String meta = "Generated by: " + generatedBy
                + "   |   Date: " + new SimpleDateFormat("yyyy-MM-dd HH:mm").format(new Date())
                + "   |   Report: " + reportType;
        Paragraph metaPara = new Paragraph(meta,
                new Font(Font.FontFamily.HELVETICA, 9, Font.ITALIC, BaseColor.GRAY));
        metaPara.setAlignment(Element.ALIGN_CENTER);
        metaPara.setSpacingAfter(10);
        document.add(metaPara);

        LineSeparator sep = new LineSeparator(1f, 100f, new BaseColor(189, 195, 199),
                Element.ALIGN_CENTER, -4);
        document.add(new Chunk(sep));

        Paragraph spacer = new Paragraph(" ");
        spacer.setSpacingAfter(8);
        document.add(spacer);
    }

    private void addStudentSubtitle(Document document, String studentEmail)
            throws DocumentException {
        Paragraph sub = new Paragraph("Student: " + studentEmail,
                new Font(Font.FontFamily.HELVETICA, 11, Font.ITALIC, BaseColor.DARK_GRAY));
        sub.setAlignment(Element.ALIGN_CENTER);
        sub.setSpacingAfter(16);
        document.add(sub);
    }

    private PdfPTable buildTable(int colCount, float[] colWidths) throws DocumentException {
        PdfPTable table = new PdfPTable(colCount);
        table.setWidthPercentage(100);
        table.setWidths(colWidths);
        table.setHeaderRows(1);
        return table;
    }

    private void addColumnHeaders(PdfPTable table, String[] colNames,
            BaseColor headerColor) {
        Font colHeaderFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
        for (String name : colNames) {
            PdfPCell hCell = new PdfPCell(new Phrase(name, colHeaderFont));
            hCell.setBackgroundColor(headerColor);
            hCell.setPadding(7);
            table.addCell(hCell);
        }
    }

    private void finalizeDocument(Document document, PdfPTable table)
            throws DocumentException {
        document.add(table);
        document.close();
    }


    private PdfPCell dataCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text != null ? text : "-", font));
        cell.setPadding(6);
        return cell;
    }

    private void addSectionHeader(PdfPTable table, String title,
            int cols, BaseColor color) {
        PdfPCell header = new PdfPCell(new Phrase(title,
                new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, BaseColor.WHITE)));
        header.setBackgroundColor(color);
        header.setColspan(cols);
        header.setPadding(8);
        table.addCell(header);
    }

    private void emptyRow(PdfPTable table, int cols, String message) {
        PdfPCell cell = new PdfPCell(new Phrase(message,
                new Font(Font.FontFamily.HELVETICA, 10, Font.ITALIC, BaseColor.GRAY)));
        cell.setColspan(cols);
        cell.setPadding(12);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }



    private void buildUserRows(PdfPTable table, List<User> userList,
            String currentAdmin) {
        Font      bodyFont     = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.BLACK);
        Font      boldBodyFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD,   BaseColor.BLACK);
        BaseColor highlight    = new BaseColor(234, 250, 241);

        for (User u : userList) {
            boolean  isCurrent = u.getEmail().equalsIgnoreCase(currentAdmin);
            String   emailText = u.getEmail() + (isCurrent ? " *" : "");
            Font     font      = isCurrent ? boldBodyFont : bodyFont;

            PdfPCell emailCell = dataCell(emailText, font);
            PdfPCell roleCell  = dataCell(u.getAppRole(), font);
            emailCell.setPadding(6);
            roleCell.setPadding(6);
            if (isCurrent) {
                emailCell.setBackgroundColor(highlight);
                roleCell.setBackgroundColor(highlight);
            }
            table.addCell(emailCell);
            table.addCell(roleCell);
        }
    }

    private void buildClassListRows(PdfPTable table, List<String[]> rows) {
        if (rows.isEmpty()) {
            emptyRow(table, 3, "No enrolled students found.");
            return;
        }
        Font      bodyFont     = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.BLACK);
        BaseColor sectionColor = new BaseColor(44, 62, 80);
        BaseColor altRow       = new BaseColor(245, 245, 245);
        String    lastCourse   = null;
        int       rowIdx       = 0;

        for (String[] row : rows) {
            String courseTitle = row[0];
            if (!courseTitle.equals(lastCourse)) {
                addSectionHeader(table, courseTitle, 3, sectionColor);
                lastCourse = courseTitle;
                rowIdx     = 0;
            }
            BaseColor bg       = (rowIdx % 2 == 0) ? BaseColor.WHITE : altRow;
            PdfPCell emailCell = dataCell(row[1], bodyFont);
            PdfPCell dateCell  = dataCell(row[2], bodyFont);
            PdfPCell statCell  = dataCell(row[3], bodyFont);
            emailCell.setBackgroundColor(bg);
            dateCell.setBackgroundColor(bg);
            statCell.setBackgroundColor(bg);
            table.addCell(emailCell);
            table.addCell(dateCell);
            table.addCell(statCell);
            rowIdx++;
        }
    }

    private void buildSubmissionRows(PdfPTable table, List<String[]> rows) {
        if (rows.isEmpty()) {
            emptyRow(table, 6, "No records found for the selected period.");
            return;
        }
        Font      bodyFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.BLACK);
        BaseColor altRow   = new BaseColor(245, 245, 245);
        int       rowIdx   = 0;

        for (String[] row : rows) {
            BaseColor bg = (rowIdx % 2 == 0) ? BaseColor.WHITE : altRow;
            for (String val : row) {
                PdfPCell cell = dataCell(val, bodyFont);
                cell.setBackgroundColor(bg);
                table.addCell(cell);
            }
            rowIdx++;
        }
    }

    private void buildLogRows(PdfPTable table, List<ActivityLog> logList) {
        if (logList.isEmpty()) {
            emptyRow(table, 6, "No records found for the selected period.");
            return;
        }
        Font             bodyFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.BLACK);
        SimpleDateFormat sdf      = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        BaseColor        altRow   = new BaseColor(245, 245, 245);
        int              rowIdx   = 0;

        for (ActivityLog log : logList) {
            String timeStr = log.getFormatDate();
            if (timeStr.isEmpty() && log.getActivityTime() != null) {
                timeStr = sdf.format(log.getActivityTime());
            }
            BaseColor bg   = (rowIdx % 2 == 0) ? BaseColor.WHITE : altRow;
            String[]  vals = {timeStr, log.getUsername(), log.getAction(),
                              log.getIpAddress(), log.getRole(), log.getSource()};
            for (String val : vals) {
                PdfPCell cell = dataCell(val, bodyFont);
                cell.setBackgroundColor(bg);
                table.addCell(cell);
            }
            rowIdx++;
        }
    }

    private void buildGradeRows(PdfPTable table, List<String[]> rows) {
        if (rows.isEmpty()) {
            emptyRow(table, 5, "No enrolled courses or assignments found.");
            return;
        }
        Font      bodyFont     = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.BLACK);
        Font      avgFont      = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD,   BaseColor.DARK_GRAY);
        BaseColor sectionColor = new BaseColor(44, 62, 80);
        BaseColor avgRowColor  = new BaseColor(235, 245, 251);
        BaseColor altRow       = new BaseColor(245, 245, 245);

        String lastCourse  = null;
        int    rowIdx      = 0;
        double scoreSum    = 0;
        int    gradedCount = 0;

        for (int i = 0; i <= rows.size(); i++) {
            String[] row       = (i < rows.size()) ? rows.get(i) : null;
            String courseTitle = (row != null) ? row[0] : null;

            if (lastCourse != null && (courseTitle == null || !courseTitle.equals(lastCourse))) {
                String avgStr = (gradedCount > 0)
                        ? String.format("%.2f / 100", scoreSum / gradedCount)
                        : "N/A";
                PdfPCell avgLabel = new PdfPCell(new Phrase("Course Average", avgFont));
                avgLabel.setColspan(3);
                avgLabel.setBackgroundColor(avgRowColor);
                avgLabel.setPadding(6);
                PdfPCell avgVal = new PdfPCell(new Phrase(avgStr, avgFont));
                avgVal.setColspan(2);
                avgVal.setBackgroundColor(avgRowColor);
                avgVal.setPadding(6);
                table.addCell(avgLabel);
                table.addCell(avgVal);
                scoreSum    = 0;
                gradedCount = 0;
                rowIdx      = 0;
            }

            if (row == null) break;

            if (!courseTitle.equals(lastCourse)) {
                addSectionHeader(table, courseTitle, 5, sectionColor);
                lastCourse = courseTitle;
                rowIdx     = 0;
            }

            BaseColor bg = (rowIdx % 2 == 0) ? BaseColor.WHITE : altRow;
            for (int c = 1; c < row.length; c++) {
                PdfPCell cell = dataCell(row[c], bodyFont);
                cell.setBackgroundColor(bg);
                table.addCell(cell);
            }

            String scoreStr = row[4];
            if (scoreStr != null && !scoreStr.equals("-")) {
                try {
                    double rawScore = Double.parseDouble(scoreStr);
                    double maxScore = Double.parseDouble(row[2]);
                    scoreSum += (maxScore > 0) ? (rawScore / maxScore) * 100.0 : 0;
                    gradedCount++;
                } catch (NumberFormatException ignored) {}
            }
            rowIdx++;
        }
    }

   

    public void generateUserReport(OutputStream os, List<User> userList,
            String currentAdmin, String headerText, String footerText,
            String titleText) throws Exception {
        Document  document = openDocument();
        setupPageEvent(document, os, headerText, footerText, currentAdmin);
        document.open();
        addReportHeader(document, headerText, titleText, currentAdmin, "All Records");
        PdfPTable table = buildTable(2, new float[]{60f, 40f});
        addColumnHeaders(table,
                new String[]{"Username / Email", "Application Role"},
                new BaseColor(52, 73, 94));
        buildUserRows(table, userList, currentAdmin);
        finalizeDocument(document, table);
    }

    public void generateOwnRecordReport(OutputStream os, List<User> userRecord,
            List<ActivityLog> logs, String currentAdmin,
            String headerText, String footerText, String titleText) throws Exception {

        Document document = openDocument();
        setupPageEvent(document, os, headerText, footerText, currentAdmin);
        document.open();
        addReportHeader(document, headerText, titleText, currentAdmin, "Own Record");

        // Section 1: Account Details
        Paragraph s1 = new Paragraph("Account Details",
                new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD, new BaseColor(200, 220, 240)));
        s1.setSpacingBefore(10);
        s1.setSpacingAfter(8);
        document.add(s1);

        PdfPTable accountTable = buildTable(2, new float[]{60f, 40f});
        addColumnHeaders(accountTable,
                new String[]{"Username / Email", "Application Role"},
                new BaseColor(52, 73, 94));
        buildUserRows(accountTable, userRecord, currentAdmin);
        document.add(accountTable);

        // Section 2: Activity History
        Paragraph s2 = new Paragraph("Activity History",
                new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD, new BaseColor(200, 220, 240)));
        s2.setSpacingBefore(24);
        s2.setSpacingAfter(8);
        document.add(s2);

        PdfPTable logTable = buildTable(5, new float[]{22f, 32f, 18f, 12f, 16f});
        logTable.setHeaderRows(1);
        addColumnHeaders(logTable,
                new String[]{"Timestamp", "Action", "IP Address", "Role", "Source"},
                new BaseColor(44, 62, 80));

        if (logs.isEmpty()) {
            emptyRow(logTable, 5, "No activity found for this account.");
        } else {
            Font      bodyFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.BLACK);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            BaseColor altRow   = new BaseColor(245, 245, 245);
            int       rowIdx   = 0;
            for (ActivityLog log : logs) {
                String timeStr = log.getFormatDate();
                if (timeStr.isEmpty() && log.getActivityTime() != null) {
                    timeStr = sdf.format(log.getActivityTime());
                }
                BaseColor bg   = (rowIdx % 2 == 0) ? BaseColor.WHITE : altRow;
                String[]  vals = {timeStr, log.getAction(), log.getIpAddress(),
                                  log.getRole(), log.getSource()};
                for (String val : vals) {
                    PdfPCell cell = dataCell(val, bodyFont);
                    cell.setBackgroundColor(bg);
                    logTable.addCell(cell);
                }
                rowIdx++;
            }
        }
        document.add(logTable);
        document.close();
    }

    public void generateClassListReport(OutputStream os, List<String[]> rows,
            String currentUser, String headerText, String footerText,
            String titleText) throws Exception {
        Document  document = openDocument();
        setupPageEvent(document, os, headerText, footerText, currentUser);
        document.open();
        addReportHeader(document, headerText, titleText, currentUser, "Class List");
        PdfPTable table = buildTable(3, new float[]{50f, 30f, 20f});
        addColumnHeaders(table,
                new String[]{"Student Email", "Enrolled Date", "Status"},
                new BaseColor(52, 73, 94));
        buildClassListRows(table, rows);
        finalizeDocument(document, table);
    }

    public void generateSubmissionReport(OutputStream os, List<String[]> rows,
            String currentUser, String headerText, String footerText,
            String titleText) throws Exception {
        Document  document = openDocument();
        setupPageEvent(document, os, headerText, footerText, currentUser);
        document.open();
        addReportHeader(document, headerText, titleText, currentUser, "Activity Log");
        PdfPTable table = buildTable(6, new float[]{18f, 20f, 22f, 22f, 10f, 8f});
        addColumnHeaders(table,
                new String[]{"Submitted At", "Course", "Student", "Assignment", "Status", "Score"},
                new BaseColor(44, 62, 80));
        buildSubmissionRows(table, rows);
        finalizeDocument(document, table);
    }

    public void generateGradeReport(OutputStream os, List<String[]> rows,
            String studentEmail, String headerText, String footerText,
            String titleText) throws Exception {
        Document  document = openDocument();
        setupPageEvent(document, os, headerText, footerText, studentEmail);
        document.open();
        addReportHeader(document, headerText, titleText, studentEmail, "Grade Report");
        addStudentSubtitle(document, studentEmail);
        PdfPTable table = buildTable(5, new float[]{35f, 12f, 18f, 12f, 23f});
        addColumnHeaders(table,
                new String[]{"Assignment", "Max Score", "Status", "Score", "Feedback"},
                new BaseColor(52, 73, 94));
        buildGradeRows(table, rows);
        finalizeDocument(document, table);
    }

    public void generateLogReport(OutputStream os, List<ActivityLog> logList,
            String currentAdmin, String headerText, String footerText,
            String titleText) throws Exception {
        Document  document = openDocument();
        setupPageEvent(document, os, headerText, footerText, currentAdmin);
        document.open();
        addReportHeader(document, headerText, titleText, currentAdmin, "Activity Log");
        PdfPTable table = buildTable(6, new float[]{18f, 22f, 25f, 13f, 10f, 12f});
        addColumnHeaders(table,
                new String[]{"Timestamp", "Username", "Action", "IP Address", "Role", "Source"},
                new BaseColor(44, 62, 80));
        buildLogRows(table, logList);
        finalizeDocument(document, table);
    }
}
