package business;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import model.ActivityLog;
import model.User;

public class PdfReportBuilder {

    public PdfReportBuilder() {
    }

    /**
     * Inner helper class to handle headers, footers, and page numbers dynamically.
     */
    private static class HeaderFooterFooterPageEvent extends PdfPageEventHelper {
        private final String headerText;
        private final String footerText;
        private final String currentAdmin;
        private final String generatedDateStr;
        private PdfTemplate totalPagesPlaceholder;
        private BaseFont baseFont;

        public HeaderFooterFooterPageEvent(String headerText, String footerText, String currentAdmin, String generatedDateStr) {
            this.headerText = headerText;
            this.footerText = footerText;
            this.currentAdmin = currentAdmin;
            this.generatedDateStr = generatedDateStr;
            try {
                this.baseFont = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            totalPagesPlaceholder = writer.getDirectContent().createTemplate(30, 16);
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            float xHeader = document.left();
            float yHeader = document.top() + 15;
            float xFooterLeft = document.left();
            float yFooter = document.bottom() - 20;
            float xFooterRight = document.right() - 30;

            // Running Header
            ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT,
                    new Phrase(headerText, new Font(Font.FontFamily.HELVETICA, 9, Font.ITALIC, BaseColor.GRAY)),
                    xHeader, yHeader, 0);

            // Left Footer: Configuration string + Metadata
            String metaFooter = footerText + " | Generated By: " + currentAdmin + " on " + generatedDateStr;
            ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_LEFT,
                    new Phrase(metaFooter, new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.DARK_GRAY)),
                    xFooterLeft, yFooter, 0);

            // Right Footer: Page Numbers "Page X of "
            String pageString = "Page " + writer.getPageNumber() + " of ";
            float textLength = baseFont.getWidthPoint(pageString, 8);
            ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_RIGHT,
                    new Phrase(pageString, new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.DARK_GRAY)),
                    xFooterRight, yFooter, 0);

            // Add the template placeholder right after the text string
            writer.getDirectContent().addTemplate(totalPagesPlaceholder, xFooterRight, yFooter - 2);
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            totalPagesPlaceholder.beginText();
            totalPagesPlaceholder.setFontAndSize(baseFont, 8);
            totalPagesPlaceholder.setColorFill(BaseColor.DARK_GRAY);
            totalPagesPlaceholder.showText(String.valueOf(writer.getPageNumber()));
            totalPagesPlaceholder.endText();
        }
    }

    /**
     * Method to generate User reports (All Records & Logged-in Admin Report).
     */
    public void generateUserReport(OutputStream os, List<User> userList, String currentAdmin, String headerText, String footerText, String titleText) throws Exception {
        // Enforce Landscape Orientation
        Document document = new Document(PageSize.A4.rotate(), 36, 36, 54, 36);
        PdfWriter writer = PdfWriter.getInstance(document, os);

        String generatedDateStr = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        writer.setPageEvent(new HeaderFooterFooterPageEvent(headerText, footerText, currentAdmin, generatedDateStr));

        document.open();

        // Document Title Block
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, BaseColor.DARK_GRAY);
        Paragraph titlePara = new Paragraph(titleText, titleFont);
        titlePara.setAlignment(Element.ALIGN_CENTER);
        titlePara.setSpacingAfter(20);
        document.add(titlePara);

        // Define Table Layout (Username, Role)
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{60f, 40f});

        // Table Header
        Font headerFont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, BaseColor.WHITE);
        PdfPCell h1 = new PdfPCell(new Phrase("Username / Email", headerFont));
        h1.setBackgroundColor(new BaseColor(52, 73, 94));
        h1.setPadding(8);
        PdfPCell h2 = new PdfPCell(new Phrase("Application Role", headerFont));
        h2.setBackgroundColor(new BaseColor(52, 73, 94));
        h2.setPadding(8);

        table.addCell(h1);
        table.addCell(h2);

        Font bodyFont = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, BaseColor.BLACK);
        Font boldBodyFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.BLACK);

        // Populate Records
        for (User u : userList) {
            boolean isCurrentAdmin = u.getEmail().equalsIgnoreCase(currentAdmin);
            String emailText = u.getEmail() + (isCurrentAdmin ? " *" : "");
            
            PdfPCell cellEmail = new PdfPCell(new Phrase(emailText, isCurrentAdmin ? boldBodyFont : bodyFont));
            PdfPCell cellRole = new PdfPCell(new Phrase(u.getAppRole(), isCurrentAdmin ? boldBodyFont : bodyFont));
            
            cellEmail.setPadding(6);
            cellRole.setPadding(6);
            
            // Alternating backgrounds for structural clean look
            if (isCurrentAdmin) {
                cellEmail.setBackgroundColor(new BaseColor(234, 250, 241)); // Light green highlight
                cellRole.setBackgroundColor(new BaseColor(234, 250, 241));
            }

            table.addCell(cellEmail);
            table.addCell(cellRole);
        }

        document.add(table);
        document.close();
    }

    /**
     * Method to generate Audit/Logs report (Time-Bound Report).
     */
    public void generateLogReport(OutputStream os, List<ActivityLog> logList, String currentAdmin, String headerText, String footerText, String titleText) throws Exception {
        Document document = new Document(PageSize.A4.rotate(), 36, 36, 54, 36);
        PdfWriter writer = PdfWriter.getInstance(document, os);

        String generatedDateStr = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        writer.setPageEvent(new HeaderFooterFooterPageEvent(headerText, footerText, currentAdmin, generatedDateStr));

        document.open();

        Paragraph titlePara = new Paragraph(titleText, new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, BaseColor.DARK_GRAY));
        titlePara.setAlignment(Element.ALIGN_CENTER);
        titlePara.setSpacingAfter(20);
        document.add(titlePara);

        // Define Table Layout (Timestamp, Username, Action, IP Address, Role, Source Module)
        PdfPTable table = new PdfPTable(6);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{18f, 22f, 25f, 13f, 10f, 12f});

        Font headerFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
        String[] headers = {"Timestamp", "Username", "Action", "IP Address", "Role", "Source"};
        for (String hText : headers) {
            PdfPCell hCell = new PdfPCell(new Phrase(hText, headerFont));
            hCell.setBackgroundColor(new BaseColor(44, 62, 80));
            hCell.setPadding(6);
            table.addCell(hCell);
        }

        Font bodyFont = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.BLACK);
        SimpleDateFormat logDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        for (ActivityLog log : logList) {
            String timeStr = log.getFormatDate();
            if(timeStr.isEmpty() && log.getActivityTime() != null) {
                timeStr = logDateFormat.format(log.getActivityTime());
            }

            table.addCell(new PdfPCell(new Phrase(timeStr, bodyFont)));
            table.addCell(new PdfPCell(new Phrase(log.getUsername(), bodyFont)));
            table.addCell(new PdfPCell(new Phrase(log.getAction(), bodyFont)));
            table.addCell(new PdfPCell(new Phrase(log.getIpAddress(), bodyFont)));
            table.addCell(new PdfPCell(new Phrase(log.getRole(), bodyFont)));
            table.addCell(new PdfPCell(new Phrase(log.getSource(), bodyFont)));
        }

        document.add(table);
        document.close();
    }
}